apply plugin: 'org.springframework.boot'

dependencies {
	implementation project(':sqs-listener')
	implementation project(':sqs-sender')
	implementation project(':metrics')
	implementation 'software.amazon.awssdk:sts'
	implementation project(':rest-consumer')
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation project(':logger')
	implementation 'org.reactivecommons.utils:object-mapper:0.1.0'
	implementation project(':r2dbc-mysql')
	implementation project(':reactive-web')
    implementation project(':model')
    implementation project(':usecase')
    implementation 'org.springframework.boot:spring-boot-starter'
    runtimeOnly('org.springframework.boot:spring-boot-devtools')
    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
    compileOnly "org.projectlombok:lombok:1.18.38"
    annotationProcessor  "org.projectlombok:lombok:1.18.38"
    testCompileOnly  "org.projectlombok:lombok:1.18.38"
    testAnnotationProcessor  "org.projectlombok:lombok:1.18.38"
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar {
    // To disable the *-plain.jar
    enabled = false
}

bootJar {
    // Sets output jar name
    destinationDirectory = layout.settingsDirectory.dir("deployment")
    archiveFileName = "${project.getParent().getName()}.${archiveExtension.get()}"
}