dependencies {
    implementation project(':model')
    implementation project(':usecase')
    implementation project(':sqs-sender')
    implementation project(':json-mapper')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'software.amazon.awssdk:sqs'
    implementation 'org.apache.logging.log4j:log4j-api'
    implementation 'org.projectlombok:lombok:1.18.38'
    annotationProcessor "org.projectlombok:lombok:1.18.34"
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}
